# Generated by Django 6.0.4 on 2026-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_notificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationrecord',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
