# Generated by Django 6.0.4 on 2026-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='intruder_photos/'),
        ),
    ]
